on:
  workflow_dispatch:
  push:
    branches:
      - 'release/1.21'

env: 
  GITHUB_TOKEN: "${{ secrets.PUBLISH_GITHUB_TOKEN }}"

permissions:
  contents: write

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'pull_request'"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: "Read Java version"
      uses: BrycensRanch/read-properties-action@v1.0.4
      id: java_version
      with:
        file: gradle.properties
        property: javaVersion

    - name: "Read MC version"
      uses: SebRollen/toml-action@v1.2.0
      id: mc_version
      with:
        file: 'gradle/libs.versions.toml'
        field: 'versions.minecraft'

    - name: "Read MC version range"
      uses: SebRollen/toml-action@v1.2.0
      id: mc_version_range
      with:
        file: 'gradle/libs.versions.toml'
        field: 'versions.minecraft-range'
        
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ steps.java_version.outputs.javaVersion }}
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Make Gradle Wrapper Executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Get version from gradle
      id: get_version
      run: echo "VERSION=$(./gradlew modVersion | grep VERSION | awk -F'=' '{print $2}')" >> $GITHUB_OUTPUT

    - name: "Show environment variables"
      run: "echo version=${{steps.get_version.outputs.VERSION}} java_version=${{ steps.java_version.outputs.javaVersion }} mc_version=${{ steps.mc_version.outputs.value }} mc_version_range=${{ steps.mc_version_range.outputs.value }}"

    - name: Build with Gradle
      run: ./gradlew build

    - name: Extract latest changelog
      id: changelog
      run: |
        latest_version=$(grep -m 1 -oP '(?<=##\s)\d+\.\d+\.\d+' CHANGELOG.md)
        latest_changelog=$(sed -n "/## $latest_version/,/## /p" CHANGELOG.md | sed '$d')
        echo "$latest_changelog" > latest_changelog.txt

    - name: Publish (Github)
      uses: softprops/action-gh-release@v2
      with:
        name: FilloaxLib ${{ steps.get_version.outputs.VERSION }} - ${{ steps.mc_version.outputs.value }}
        body_path: latest_changelog.txt
        token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
        make_latest: true
        tag_name: "${{ steps.get_version.outputs.VERSION }}-${{steps.mc_version.outputs.value}}"
        target_commitish: ${{ env.GITHUB_SHA }}
        files: |
          base/build/libs/*.jar
          fabric/build/libs/*.jar
          neoforge/build/libs/*.jar

    - uses: Kir-Antipov/mc-publish@v3.3
      name: Publish (Online, Fabric)
      with:
        modrinth-token: ${{ secrets.TOKEN_MODRINTH }}

        name: FilloaxLib ${{ steps.get_version.outputs.VERSION }} - ${{ steps.mc_version.outputs.value }} Fabric
        version-type: beta

        game-versions: ${{ steps.mc_version_range.outputs.value }}
        dependencies: |
          fabric-language-kotlin(required)
          fabric-api(required)
        java: ${{ steps.java_version.outputs.javaVersion }}

        changelog-file: latest_changelog.txt
        files: |
          fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
          fabric/build/libs/*-@(dev|sources|javadocs).jar

    - uses: Kir-Antipov/mc-publish@v3.3
      name: Publish (Online, Neoforge)
      with:
        modrinth-token: ${{ secrets.TOKEN_MODRINTH }}

        loaders: neoforge
        modrinth-id: JAKPaut3
        version: "${{ steps.get_version.outputs.VERSION }}-${{ steps.mc_version.outputs.value }}-neoforge"

        name: FilloaxLib ${{ steps.get_version.outputs.VERSION }} - ${{ steps.mc_version.outputs.value }} Neoforged
        version-type: beta

        game-versions: ${{ steps.mc_version_range.outputs.value }}
        dependencies:
        java: ${{ steps.java_version.outputs.javaVersion }}

        changelog-file: latest_changelog.txt
        files: |
          neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar
          neoforge/build/libs/*-@(dev|sources|javadocs).jar

    - name: Trigger Jitpack build
      run: |
        curl -L https://jitpack.io/com/github/filloax/filloaxlib/${{ env.TAG }}/filloaxlib-${{ env.TAG }}.pom &
      env:
        TAG: "${{ steps.get_version.outputs.VERSION }}-${{steps.mc_version.outputs.value }}"
