on:
  workflow_dispatch:
  push:
    branches:
      - 'release/1.21'

#Environment variables that can later be referenced using ${{ env.MINECRAFT_VERSION }}. These are useful for repeating information and allow for quick changes for new mod updates
env: 
  JAVA_VERSION: 21                   
  # RELEASE_NAME: FxLib
  GITHUB_TOKEN: "${{ secrets.PUBLISH_GITHUB_TOKEN }}"
  MINECRAFT_VERSION: 1.21
  MC_VER_EXTRA: 1.21.1    # Minor releases that are still compatible

permissions:
  contents: write

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'pull_request'"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Make Gradle Wrapper Executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Get version from gradle
      id: get_version
      run: echo "VERSION=$(./gradlew modVersion | grep VERSION | awk -F'=' '{print $2}')" >> $GITHUB_OUTPUT

    - name: Build with Gradle
      run: ./gradlew build

    - name: Extract latest changelog
      id: changelog
      run: |
        latest_version=$(grep -m 1 -oP '(?<=##\s)\d+\.\d+\.\d+' CHANGELOG.md)
        latest_changelog=$(sed -n "/## $latest_version/,/## /p" CHANGELOG.md | sed '$d')
        echo "$latest_changelog" > latest_changelog.txt

    - name: Publish (Github)
      uses: softprops/action-gh-release@v2
      with:
        name: FilloaxLib ${{ steps.get_version.outputs.VERSION }} - ${{ env.MINECRAFT_VERSION }}
        body_path: latest_changelog.txt
        token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
        make_latest: true
        tag_name: "${{ steps.get_version.outputs.VERSION }}-${{env.MINECRAFT_VERSION}}"
        target_commitish: ${{ env.GITHUB_SHA }}
        files: |
          base/build/libs/*.jar
          fabric/build/libs/*.jar
          neoforge/build/libs/*.jar

    - uses: Kir-Antipov/mc-publish@v3.3
      name: Publish (Online, Fabric)
      with:
        modrinth-token: ${{ secrets.TOKEN_MODRINTH }}

        name: FilloaxLib ${{ steps.get_version.outputs.VERSION }} - ${{ env.MINECRAFT_VERSION }} Fabric
        version-type: beta

        game-versions: |
          ${{ env.MINECRAFT_VERSION }}
          ${{ env.MC_VER_EXTRA }}
        dependencies: |
          fabric-language-kotlin(required)
          fabric-api(required)
        java: 21

        changelog-file: latest_changelog.txt
        files: |
          fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
          fabric/build/libs/*-@(dev|sources|javadocs).jar

    - uses: Kir-Antipov/mc-publish@v3.3
      name: Publish (Online, Neoforge)
      with:
        modrinth-token: ${{ secrets.TOKEN_MODRINTH }}

        name: FilloaxLib ${{ steps.get_version.outputs.VERSION }} - ${{ env.MINECRAFT_VERSION }} Neoforged
        version-type: beta

        game-versions: |
          ${{ env.MINECRAFT_VERSION }}
          ${{ env.MC_VER_EXTRA }}
        dependencies:
        java: 21

        changelog-file: latest_changelog.txt
        files: |
          neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar
          neoforge/build/libs/*-@(dev|sources|javadocs).jar

    - name: Trigger Jitpack build
      run: |
        curl -L https://jitpack.io/com/github/filloax/filloaxlib/${{ env.TAG }}/filloaxlib-${{ env.TAG }}.pom &
      env:
        TAG: "${{ steps.get_version.outputs.VERSION }}-${{env.MINECRAFT_VERSION }}"
